config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'articles#index'

  namespace :dashboard do
    root to: 'base#index'
    resource :profile, only: [:edit, :update, :show], controller: 'profiles'
    resource :site_settings, only: [:edit, :update, :show], controller: 'site_settings'
    resources :articles, only: [:new, :create, :edit, :update, :destroy, :index, :show]

    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end

  resources :articles, only: [:index, :show] do
    collection do
      get :feed, defaults: { format: 'rss' }
    end
  end

  post '/images', to: 'images#create'

end

app/models/site_setting.rb
class SiteSetting < ApplicationRecord
  validates :site_title, presence: true
  validates :site_description, presence: true
  validates :site_meta_description, length: { maximum: 120 }
  validate :validate_copyright_url

  private

  def validate_copyright_url
    return if copyright_url.blank?

    # URL または '/' で始まるパスかをチェック
    uri = URI.parse(copyright_url)
    unless uri.is_a?(URI::HTTP) || uri.is_a?(URI::HTTPS) || copyright_url.starts_with?('/')
      errors.add(:copyright_url, 'は有効なURLまたはルートパスである必要があります')
    end
  rescue URI::InvalidURIError
    errors.add(:copyright_url, 'は有効なURLフォーマットである必要があります')
  end
end

app/controllers/dashboard/site_settings_controller.rb
module Dashboard
  class SiteSettingsController < ApplicationController
    before_action :authenticate_user
    before_action :set_site_setting, only: [:edit, :update]

    def show
      redirect_to edit_dashboard_site_settings_path
    end

    def edit
    end

    def update
      if @site_setting.update(site_setting_params)
        flash[:notice] = 'サイト設定が更新されました。'
        redirect_to dashboard_root_path
      else
        flash.now[:alert] = @site_setting.errors.full_messages
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_site_setting
      @site_setting = SiteSetting.first_or_initialize
    end

    def site_setting_params
      params.require(:site_setting).permit(
        :site_title, :site_description,
        :site_meta_description, :copyright,
        :copyright_url
      )
    end
  end
end

app/views/site_settings/edit.html.slim
- content_for(:title, '記事内容変更')
- content_for(:current, 'site_settings')

main.page
  - if @site_setting.errors.any?
    div style='color: red'
      h2
        = t('errors.template.header', model: SiteSetting.model_name.human, count: @site_setting.errors.count)
      ul
        - @site_setting.errors.full_messages.each do |message|
          li = message
  .page__body
    .a-container.is-md
      .page__body-inner
        = form_with model: @site_setting, url: site_settings_path, local: true, class: 'form' do |form|
          .form__items
            .form-item
              .form-item__rows
                .form-item__row
                  = form.label :site_title, 'サイトタイトル', class: 'a-form-label'
                .form-item__row
                  = form.text_field :site_title, class: 'a-text-input'
            .form-item
              .form-item__rows
                .form-item__row
                  = form.label :site_description, 'サイトの説明', class: 'a-form-label'
                .form-item__row
                  = form.text_area :site_description, class: 'a-text-input is-sm'
            .form-item
              .form-item__rows
                .form-item__row
                  = form.label :site_meta_description, 'meta description', class: 'a-form-label'
                .form-item__row
                  = form.text_area :site_meta_description, class: 'a-text-input is-sm'
                .form-item__row
                  .a-form-help
                    p
                      | 120字以内を目安に。
            .form-item
              .form-item__rows
                .form-item__row
                  = form.label :copyright, 'Copyright', class: 'a-form-label'
                .form-item__row
                  = form.text_field :copyright, class: 'a-text-input'
            .form-item
              .form-item__rows
                .form-item__row
                  = form.label :copyright_url, 'Copyrightのリンク', class: 'a-form-label'
                .form-item__row
                  = form.text_field :copyright_url, class: 'a-text-input'

          .form__actions
            .form__action
              = button_tag '更新', type: 'submit', name: 'publish', class: 'a-button is-lg is-primary', data: { turbo: false }